pipeline{
    agent any
    stages{
      stage('Start'){
          steps{
          echo 'Start the pipeline'
          }
      }
      
      stage('Clean'){
          steps{
            bat 'mvn clean'
          }
      }
      
      stage('Install'){
          steps{
            bat 'mvn install'
          }
      }
        
      
      stage('Sonar'){
          steps{
            bat 'mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.analysis.mode=publish'
          }
      }
    }
}
