pipeline{
    agent any
    stages{
      stage('Start'){
          steps{
          echo 'Start the pipeline'
          }
      }
      
      stage('Clean'){
          steps{
          
          }
      }
      
      stage('Install'){
          steps{
          
          }
      }
    }
}
